# Generated by Django 6.0.4 on 2026-04-16 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
